Repository ministryofjustice/fala, pull requests merged in 2024-07, with the labels that each got.

#283 EL-1489: Remove modular & use GOVUK frontend
  fala/assets-src/images/favicon.ico
  fala/assets-src/images/favicon.svg
  fala/assets-src/images/fonts/bold-affa96571d-v2.woff
  fala/assets-src/images/fonts/bold-b542beb274-v2.woff2
  fala/assets-src/images/fonts/light-94a07e06a1-v2.woff2
  fala/assets-src/images/fonts/light-f591b13f7d-v2.woff
  fala/assets-src/images/govuk-crest-2x.png
  fala/assets-src/images/govuk-crest.png
  fala/assets-src/images/govuk-icon-180.png
  fala/assets-src/images/govuk-icon-192.png
  fala/assets-src/images/govuk-icon-512.png
  fala/assets-src/images/govuk-icon-mask.svg
  fala/assets-src/images/govuk-opengraph-image.png
  fala/assets-src/images/icons/icon-cross-2x.png
  fala/assets-src/images/icons/icon-cross.png
  fala/assets-src/images/icons/icon-dropdown-2x.png
  fala/assets-src/images/icons/icon-dropdown.png
  fala/assets-src/images/icons/icon-location-2x.png
  fala/assets-src/images/icons/icon-location.png
  fala/assets-src/images/icons/icon-numbered-markers-2x.png
  fala/assets-src/images/icons/icon-pointer-2x.png
  fala/assets-src/images/icons/icon-pointer.png
  fala/assets-src/images/icons/icon-remove-2x.png
  fala/assets-src/images/icons/icon-remove.png
  fala/assets-src/images/icons/icon-small-cross-2x.png
  fala/assets-src/images/icons/icon-small-cross.png
  fala/assets-src/sass/_fala-results-js.scss
  fala/assets-src/sass/_fala-results-print.scss
  fala/assets-src/sass/_fala-results.scss
  fala/assets-src/sass/_fala-search.scss
  fala/assets-src/sass/_tabs.scss
  fala/assets-src/sass/main.scss
  fala/assets-src/scripts/main.js
  fala/templates/adviser/results.html
  fala/templates/adviser/scotland_warning.html
  fala/templates/adviser/search.html
  fala/templates/base.html
  fala/templates/external.html
  fala/templates/generic-py-base.html
  fala/templates/research_banner.html
  gulpfile.js
  package-lock.json
  package.json
  webpack.config.js
  webpack.config.prod.js
Labels: Approved

#263 EL-1508 add new feedback table
  Dockerfile
  fala/apps/adviser/migrations/0001_initial.py
  fala/apps/adviser/migrations/__init__.py
  fala/apps/adviser/models.py
  fala/migrate_db.sh
  fala/settings/base.py
  kubernetes_deploy/production/migrate-db-job.yml
  kubernetes_deploy/staging/deployment.yml
  kubernetes_deploy/staging/migrate-db-job.yml
Labels: Ready for review

#298 Microsoft just broke our build
  Dockerfile-playwright
  requirements/generated/requirements-dev.txt
  requirements/source/requirements-dev.in
Labels: Approved

#278 EL-1463 add helm and multi deploys
  .circleci/config.yml
  bin/deploy.sh
  fala/settings/base.py
  helm_deploy/laa-fala/.helmignore
  helm_deploy/laa-fala/Chart.lock
  helm_deploy/laa-fala/Chart.yaml
  helm_deploy/laa-fala/charts/postgresql-11.9.13.tgz
  helm_deploy/laa-fala/templates/NOTES.txt
  helm_deploy/laa-fala/templates/_envs.tpl
  helm_deploy/laa-fala/templates/_helpers.tpl
  helm_deploy/laa-fala/templates/deployment.yaml
  helm_deploy/laa-fala/templates/hpa.yaml
  helm_deploy/laa-fala/templates/ingress.yaml
  helm_deploy/laa-fala/templates/service.yaml
  helm_deploy/laa-fala/templates/serviceaccount.yaml
  helm_deploy/laa-fala/templates/tests/test-connection.yaml
  helm_deploy/laa-fala/values/fala-production.yaml
  helm_deploy/laa-fala/values/fala-staging.yaml
  helm_deploy/laa-fala/values/fala-uat.yaml
Labels: Ready for review

#300 update feature flag settings
  kubernetes_deploy/development/deployment.yml
  kubernetes_deploy/production/deployment.yml
  kubernetes_deploy/staging/deployment.yml
Labels: Approved

#301 rename ingress to comply with naming requirements
  .circleci/config.yml
  helm_deploy/laa-fala/values/fala-production.yaml
Labels: Ready for review

#303 Remove old files which were missed in previous tickets
  README.md
  fala/assets-src/scripts/find-legal-adviser.js
  fala/assets-src/scripts/main.js
  fala/management/commands/rewrite_paths_in_static_files.py
  fala/settings/base.py
  run_local.sh
Labels: Approved

#302 Add ingress name
  helm_deploy/laa-fala/templates/ingress.yaml
  helm_deploy/laa-fala/values/fala-production.yaml
  helm_deploy/laa-fala/values/fala-staging.yaml
Labels: Approved

#304 update service account name for production
  helm_deploy/laa-fala/values/fala-production.yaml
Labels: Approved

#290 DRY up category selection, moving methods
  fala/apps/adviser/templatetags/adviser_extras.py
  fala/apps/adviser/views.py
  fala/templates/adviser/results.html
Labels: Approved

#299 EL-1538: Add Django Jinja2 templates
  fala/jinja2.py
  fala/settings/base.py
  fala/templates/adviser/search.html
  requirements/generated/requirements-dev.txt
  requirements/generated/requirements-production.txt
  requirements/source/requirements-base.in
Labels: UAT, Approved

#296 EL-1453 Replace gulp with django-webpack-loader
  .circleci/config.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  fala/apps/adviser/migrations/0001_initial.py
  fala/assets-src/sass/main.scss
  fala/settings/base.py
  fala/settings/test.py
  fala/templates/base.html
  fala/templates/external.html
  fala/templates/favicon.ico
  fala/templates/generic-py-base.html
  fala/urls.py
  gulpfile.js
  package-lock.json
  package.json
  requirements/generated/requirements-dev.txt
  requirements/generated/requirements-production.txt
  requirements/source/requirements-base.in
  webpack.config.js
Labels: UAT, Approved

#307 EL-1621 delete old helm deployments
  .github/actions/delete-uat-release/action.yml
  .github/workflows/delete_uat_release.yml
Labels: Approved

#311 Revert "EL-1453 Replace gulp with django-webpack-loader (#296)"
  .circleci/config.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  fala/apps/adviser/migrations/0001_initial.py
  fala/assets-src/sass/main.scss
  fala/settings/base.py
  fala/settings/test.py
  fala/templates/base.html
  fala/templates/external.html
  fala/templates/favicon.ico
  fala/templates/generic-py-base.html
  fala/urls.py
  gulpfile.js
  package-lock.json
  package.json
  requirements/generated/requirements-dev.txt
  requirements/generated/requirements-production.txt
  requirements/source/requirements-base.in
  webpack.config.js
Labels: UAT, Approved

#312 Revert "DRY up category selection, moving methods (#290)"
  fala/apps/adviser/templatetags/adviser_extras.py
  fala/apps/adviser/views.py
  fala/templates/adviser/results.html
Labels: Ready for review

#315 EL-1618 update deployment pipeline
  .circleci/config.yml
Labels: Approved

#305 EL-1452: Remove feature flag & redundant code
  .circleci/config.yml
  .env.example
  fala/apps/adviser/forms.py
  fala/apps/adviser/tests/test_crown_dependencies_view.py
  fala/apps/adviser/tests/test_search_view_function.py
  fala/apps/adviser/views.py
  fala/assets-src/sass/main.scss
  fala/settings/base.py
  fala/settings/production.py
  fala/templates/500.html
  fala/templates/adviser/_results.html
  fala/templates/adviser/accessibility-statement_old.html
  fala/templates/adviser/results.html
  fala/templates/adviser/search_old.html
  fala/templates/ajax-base.html
  fala/templates/base.html
  fala/templates/feedback/confirmation.html
  fala/templates/feedback/email.html
  fala/templates/feedback/index.html
  fala/templates/footer.html
  helm_deploy/laa-fala/templates/_envs.tpl
  kubernetes_deploy/development/deployment.yml
  kubernetes_deploy/production/deployment.yml
  kubernetes_deploy/staging/deployment.yml
Labels: UAT, Approved

#308 EL-1481: Playwright setup
  .circleci/config.yml
  Dockerfile
  Dockerfile-playwright
  README.md
  docker-compose.yml
  fala/apps/adviser/tests/test_results_page_journeys_playwright.py
  fala/apps/adviser/tests/test_search_page_journeys_playwright.py
  fala/playwright/setup.py
  playwright/e2e/test_example.py
  run_local.sh
Labels: Approved

#314 EL-1627: Refactor category methods, without breaking pagination links
  fala/apps/adviser/templatetags/adviser_extras.py
  fala/apps/adviser/tests/test_search_view_function.py
  fala/apps/adviser/views.py
  fala/templates/adviser/results.html
Labels: UAT, Approved

#317 EL-1621 update trigger for Github Action STG deletion
  .github/actions/delete-uat-release/action.yml
  .github/workflows/delete_uat_release.yml
Labels: Approved

#321 Remove unused code missed during removal of old FALA code
  fala/apps/adviser/views.py
Labels: UAT, Approved

#323 EL-1619: Deploy staging with helm
  .circleci/config.yml
  helm_deploy/laa-fala/values/fala-staging.yaml
  kubernetes_deploy/staging/ingress.yml
Labels: Approved

#322 EL-1647 upgrade jquery to fix sec vulns
  fala/templates/generic-py-base.html
Labels: UAT, Approved

#319 EL-1559: Write FALA specific e2e playwright tests
  fala/apps/adviser/tests/page_objects.py
  fala/apps/adviser/tests/test_fala_views_and_functions.py
  fala/apps/adviser/tests/test_other_regions_playwright.py
  fala/apps/adviser/tests/test_other_regions_view.py
  fala/apps/adviser/tests/test_pagination_playwright.py
  fala/apps/adviser/tests/test_results_page_journeys_playwright.py
  fala/apps/adviser/tests/test_search_page_journeys_playwright.py
  fala/apps/adviser/tests/test_translation_playwright.py
  fala/playwright/setup.py
Labels: UAT, Approved
