Repository ministryofjustice/fala, pull requests merged in 2024-08, with the labels that each got.

#328 EL-1626: Translating postcode, organisation & categories fields in grey box on results page
  fala/apps/adviser/tests/page_objects.py
  fala/templates/adviser/results.html
Labels: UAT, Approved

#326 EL-1658: Add migrate job to helm templates
  helm_deploy/laa-fala/Chart.lock
  helm_deploy/laa-fala/Chart.yaml
  helm_deploy/laa-fala/charts/postgresql-11.9.13.tgz
  helm_deploy/laa-fala/templates/_envs.tpl
  helm_deploy/laa-fala/templates/deployment.yaml
  helm_deploy/laa-fala/templates/migrate.yaml
  helm_deploy/laa-fala/templates/service.yaml
  helm_deploy/laa-fala/values/fala-uat.yaml
Labels: Approved

#327 EL-1607 Incorporate jinja2 template macros
  fala/apps/adviser/forms.py
  fala/apps/adviser/templatetags/adviser_extras.py
  fala/apps/adviser/tests/test_fala_views_and_functions.py
  fala/apps/adviser/views.py
  fala/templates/adviser/results.html
  fala/templates/adviser/scotland_warning.html
  fala/templates/adviser/search.html
  fala/templates/base.html
  fala/templates/generic-py-base.html
Labels: UAT, Approved

#332 Create a new browser context for each test
  fala/playwright/setup.py
Labels: Ready for review

#333 EL-1561 Sort FALA categories by name not by abbreviation code
  fala/apps/laalaa/api.py
Labels: UAT, Approved

#331 EL-1690: Create Cookie Policy Page
  fala/apps/adviser/tests/page_objects.py
  fala/apps/adviser/tests/test_cookies_page_journeys_playwright.py
  fala/apps/adviser/views.py
  fala/assets-src/sass/main.scss
  fala/playwright/setup.py
  fala/templates/adviser/cookies.html
  fala/templates/footer.html
  fala/templates/generic-py-base.html
  fala/urls.py
Labels: UAT, Approved

#338 EL-1697 use commit hash as part of ECR image tag
  .circleci/config.yml
  bin/deploy.sh
Labels: Ready for review

#335 EL-1655 FALA production helm deploy
  .circleci/config.yml
  helm_deploy/laa-fala/values/fala-production.yaml
  kubernetes_deploy/production/ingress.yml
Labels: Approved

#341 EL-1697 use branch hash in ECR tag name
  .circleci/config.yml
  bin/deploy.sh
Labels: Approved

#336 EL-1507: Pre-populated-url
  fala/apps/adviser/forms.py
  fala/apps/adviser/tests/page_objects.py
  fala/apps/adviser/tests/test_search_page_journeys_playwright.py
  fala/apps/adviser/views.py
  fala/playwright/setup.py
Labels: UAT, Approved

#339 EL-1698 addressed LAALAA API being called for scotland postcode region
  fala/apps/adviser/forms.py
  fala/apps/adviser/tests/test_other_regions_view.py
Labels: Approved

#337 EL-1550: Update cookie banner
  .circleci/config.yml
  fala/apps/adviser/tests/test_cookies_page_journeys_playwright.py
  fala/assets-src/sass/main.scss
  fala/assets-src/scripts/cookies.js
  fala/assets-src/scripts/main.js
  fala/templates/adviser/_cookie_banner.html
  fala/templates/base.html
  fala/templates/generic-py-base.html
  gulpfile.js
Labels: UAT, Approved

#343 EL-1640 Removing delete pvc command. Not required
  .github/actions/delete-uat-release/action.yml
Labels: UAT, Approved

#346 EL-1716 remove certificate
  kubernetes_deploy/production/ingress.yml
Labels: bug, Approved
