Repository ministryofjustice/fala, pull requests merged in 2024-09, with the labels that each got.

#344 EL-1711: Fix font size on Cat of Law
  fala/templates/adviser/search.html
Labels: UAT, Approved

#348 EL-1718: Remove word 'test' from cookie banner
  fala/templates/adviser/_cookie_banner.html
Labels: Ready for review

#347 EL-1605: Upgrade Node to v20
  .circleci/config.yml
  .nvmrc
  Dockerfile
  docs/virtual-env.md
  gulpfile.js
  package-lock.json
  package.json
Labels: Approved

#349 EL 1656 remove k8s deploy directory
  .circleci/config.yml
  .circleci/deploy_to_kubernetes
  README.md
  dashboards/production/pods-dashboard.yml
  dashboards/staging/ingress-dashboard.yml
  dashboards/staging/pods-dashboard.yml
  docs/kubernetes.md
  kubernetes_deploy/development/dashboard.yml
  kubernetes_deploy/development/deployment.yml
  kubernetes_deploy/development/ingress.yml
  kubernetes_deploy/development/service.yml
  kubernetes_deploy/production/deployment.yml
  kubernetes_deploy/production/ingress.yml
  kubernetes_deploy/production/migrate-db-job.yml
  kubernetes_deploy/production/service.yml
  kubernetes_deploy/staging/deployment.yml
  kubernetes_deploy/staging/ingress.yml
  kubernetes_deploy/staging/migrate-db-job.yml
  kubernetes_deploy/staging/service.yml
Labels: Approved

#353 EL-1686: Update content based on accessibility report
  fala/apps/adviser/forms.py
  fala/apps/adviser/tests/test_fala_views_and_functions.py
  fala/apps/adviser/tests/test_search_page_journeys_playwright.py
  fala/templates/adviser/results.html
  fala/templates/adviser/search.html
Labels: UAT, Approved

#351 EL-1687: 'No results' hierarchy
  fala/apps/adviser/tests/test_search_page_journeys_playwright.py
  fala/assets-src/sass/main.scss
  fala/assets-src/scripts/cookies.js
  fala/templates/adviser/results.html
  fala/templates/macros/element.html
  gulpfile.js
Labels: UAT, Approved

#352 EL-1574: Add HTML titles
  fala/templates/adviser/accessibility_statement.html
  fala/templates/adviser/cookies.html
  fala/templates/adviser/other_region.html
  fala/templates/adviser/privacy.html
  fala/templates/adviser/results.html
Labels: UAT, Approved

#354 EL-1599: Padding on categories list
  fala/templates/adviser/results.html
Labels: Approved

#356 EL-1751: `form_submission` event not firing in GA4
  fala/assets-src/scripts/google_tag_manager_data_layer.js
  fala/templates/adviser/search.html
  fala/templates/base.html
  fala/templates/macros/forms.html
  gulpfile.js
Labels: UAT, Approved
