Repository ministryofjustice/fala, pull requests merged in 2024-05, with the labels that each got.

#246 El 1468 grafana dashboards
  .circleci/config.yml
  kubernetes_deploy/staging/ingress-dashboard.yml
  kubernetes_deploy/staging/pods-dashboard.yml
Labels: Approved

#251 EL-1468 follow up - fix prod deploy by using separate grafana deploy
  .circleci/config.yml
Labels: Ready for review

#245 El 1434 results page rework
  fala/apps/adviser/tests/test_search_view_function.py
  fala/assets-src/sass/main.scss
  fala/templates/adviser/results.html
Labels: UAT, Approved

#250 EL:1473: Replace local.py with .env
  .env.example
  .gitignore
  README.md
  docker-compose.yml
  fala/settings/base.py
  fala/settings/local.example.py
  fala/templates/adviser/search.html
  requirements/generated/requirements-dev.txt
  requirements/generated/requirements-lint.txt
  requirements/generated/requirements-pre-commit.txt
  requirements/generated/requirements-production.txt
  requirements/source/requirements-base.in
  run_local.sh
Labels: UAT, Approved

#252 NO-TICKET: Update README with test instructions
  docs/virtual-env.md
Labels: Approved

#243 EL-1436 google map link on results page
  fala/apps/adviser/templatetags/adviser_extras.py
  fala/apps/adviser/tests/test_adviser_extras.py
  fala/assets-src/sass/main.scss
  fala/templates/adviser/results.html
Labels: UAT, Approved

#248 EL-1435: Display params on results page and allow return to search
  fala/apps/adviser/tests/test_search_view_function.py
  fala/apps/adviser/views.py
  fala/templates/adviser/results.html
  fala/templates/macros/element.html
Labels: Approved

#256 EL-1513 - FALA name links to root url path
  fala/templates/generic-py-base.html
Labels: UAT, Approved

#240 El 1433 crown dependencies results
  fala/apps/adviser/forms.py
  fala/apps/adviser/regions.py
  fala/apps/adviser/tests/test_crown_dependencies_view.py
  fala/apps/adviser/tests/test_search_view_function.py
  fala/apps/adviser/views.py
  fala/templates/adviser/other_region.html
  fala/templates/adviser/results.html
  fala/templates/adviser/search.html
Labels: UAT, Approved

#257 EL-1515 remove awkward padding on results page when distance not present
  fala/assets-src/sass/main.scss
  fala/templates/adviser/results.html
Labels: UAT, Approved

#258 EL-1502: Add postgres db to circleci config
  .circleci/config.yml
  .env.example
  docker-compose.yml
  docs/virtual-env.md
  fala/settings/base.py
  requirements/generated/requirements-dev.txt
  requirements/generated/requirements-lint.txt
  requirements/generated/requirements-pre-commit.txt
  requirements/generated/requirements-production.txt
  requirements/source/requirements-base.in
Labels: Approved

#262 EL-1447: Update checkboxes `id` label
  fala/templates/adviser/search.html
  fala/templates/adviser/search_old.html
Labels: Approved

#264 EL-1447: Add `id` to change search button
  fala/templates/adviser/other_region.html
Labels: Approved

#259 EL-1467 Add Research banner
  .env.example
  fala/apps/adviser/tests/test_search_view_function.py
  fala/apps/adviser/views.py
  fala/assets-src/sass/main.scss
  fala/settings/base.py
  fala/templates/adviser/results.html
  fala/templates/research_banner.html
  kubernetes_deploy/development/deployment.yml
  kubernetes_deploy/production/deployment.yml
  kubernetes_deploy/staging/deployment.yml
Labels: Approved

#265 El-1447: Add `dataLayer` variables for GA4
  fala/templates/adviser/search.html
  fala/templates/base.html
Labels: Approved

#260 EL-1527: Add org name to google map link
  fala/apps/adviser/templatetags/adviser_extras.py
  fala/apps/adviser/tests/test_adviser_extras.py
  fala/templates/adviser/results.html
Labels: UAT, Approved
